version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: tp_b2
      # You should definitely change the password in production
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - database_data:/var/lib/postgresql/data:rw
  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_DEFAULT_EMAIL: quentindutilleul@pm.me
    ports:
      - 90:80

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
